repository: kamalexio/kamalexio.github.io

version: 2

name: A K
title: Aleksandr Kaminskii
email: 03yurt_lawns@icloud.com

darkmode: false

github_username: kamalexio

about_title: About Me
about_profile_image: images/profile.jpeg
about_content: |
  Welcome!

  My name is Aleksandr, I am a Finance Manager currently working in Banking sector.
  
  In my humble opinion, I am most skilled in Finance and IT.
  
  I do work for some side projects on GitHub,<br>
    which include but are not limited to algorithmic trading and sport data science (mostly football / soccer).

  If You are interested - my detailed core experience is below.

  A K

content:
  - title: Experience
    layout: list
    content:
      - layout: right
        border: weak
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        description: Description of role
    content:  
      - layout: left
        border: weak
        title: SAS
        sub_title: Management Reporting
        caption: 2020 - now
        description: Heavy usage


footer_show_references: false
remote_theme: sproogen/resume-theme