repository: kamalexio/kamalexio.github.io

version: 2

name: A K
title: Aleksandr Kaminskii
email: 03yurt_lawns@icloud.com

darkmode: false

github_username: kamalexio

about_profile_image: images/profile.jpeg
about_content: |
  Welcome!

  My name is Aleksandr, I am a Finance Manager currently working in Banking sector.
  
  In my humble opinion, I am most skilled in Finance and IT.
  
  I do work for some side projects on GitHub,<br>
    which include but are not limited to algorithmic trading and sport data science (mostly football / soccer).

  If You are interested - my detailed core coding experience is below.

  A K

content:

  - title: Core Coding Experience
    layout: list
    content:

      - layout: center
        border: weak
        title: SAS
        sub_title: Management Reporting
        caption: 2020 - now
      
      - layout: center
        border: weak
        title: SQL
        sub_title: Management Reporting
        caption: 2020 - now

      - layout: center
        border: weak
        title: Python
        sub_title: Side Projects & Management Reporting
        caption: 2019 - now

      - layout: center
        border: weak
        title: Pine
        sub_title: Side Projects
        caption: 2022 - now

      - layout: center
        border: weak
        title: Swift
        sub_title: Side Projects
        caption: 2024 - now

footer_show_references: false
remote_theme: sproogen/resume-theme