# Site
repository: kamalexio/kamalexio.github.io

# Content configuration version
version: 2

# Personal info
name: A K
title: Aleksandr Kaminskii
email: 03yurt_lawns@icloud.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: kamalexio

# About Section
about_title: 
about_profile_image: images/profile.jpeg
about_content: |
  Welcome!

  My name is Aleksandr, I am a Finance Manager currently working in Banking sector.
  
  In my humble opinion, I am most skilled in Finance and IT.
  
  I do work for some side projects on GitHub,<br>
    which include but are not limited to algorithmic trading and sport data science (mostly football / soccer).

  If You are interested - my detailed core experience is below.

  A K

—Åontent:
  - title: Core Experience
    layout: list
    content:   
      - layout: left
        border: weak
        title: SAS
        sub_title: Management Reporting
        caption: 2020 - now
        description: Heavy usage

      - layout: left
        border: weak
        title: SQL
        sub_title: Management Reporting
        caption: 2020 - now
        description: Heavy usage

      - layout: left
        border: weak
        title: Python
        sub_title: Side Projects & Management Reporting
        caption: 2019 - now
        description: Medium usage
      
      - layout: left
        border: weak
        title: Pine
        sub_title: Side Projects
        caption: 2022 - now
        description: Medium usage

      - layout: left
        border: weak
        title: Swift
        sub_title: Side Projects
        caption: 2024 - now
        description: Light usage

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme